### ISSUE TITLE
fb-adb Is Missing

### ISSUE THREAD

**Issue by felicianotech** [circleci/image-builder#102]
This was available in Ubuntu 12.04 but missing from Ubuntu 14.04. This is a very useful tool to have when doing Android work. If Android tools are available, with this package being < 1MB, I believe we should include this too. The GitHub project has a release page for it: https://github.com/facebook/fb-adb/releases

Description: "A better shell for Android devices". Allows users to easily take screenshots.

**Comment by drazisil** [comment]
I also have a raw build at https://github.com/drazisil/fb-adb/releases that I've been using in our Canaries.

**Comment by kimh** [comment]
The reason why we were not installing fb-adb is because it required Android NDK which we haven't installed either. The reason why haven't installed is ndk is pretty huge.

```
ubuntu@box358:~$ du -sh /usr/local/android-ndk
3.4G    /usr/local/android-ndk
```

Do we have many support requests to use android-ndk?

**Comment by drazisil** [comment]
No, but we should probably remove it from our docs if we arnt going to put it on the image @felicianotech

**Comment by felicianotech** [comment]
Ah okay that sucks. @drazisil The follow up will be tracked here: https://github.com/circleci/circleci-docs/issues/353

Thanks.

**Comment by ubuntudroid** [comment]
@drazisil Why not include your raw build in circle's containers? fb-adb is an extremely useful tool especially for taking screenshots during UI testing.
