### ISSUE TITLE
Mention Packages That Should Not Be Removed

### ISSUE THREAD

**Issue by xanderdunn** [circleci/image-builder#79]
Some steps in the provided Dockerfile should not be removed, or they'll break all CircleCI builds.  For instance, even if I'm not making use of mysql or postgres, I should not remove their installation from my custom CircleCI image because they're referenced in all CircleCI runs:
<img width="548" alt="screen shot 2016-05-23 at 12 24 01" src="https://cloud.githubusercontent.com/assets/1313618/15481873/a3076fd8-20e1-11e6-9f70-9af33473dc46.png">

**Comment by jungziege** [comment]
Addressed, closing.
