### ISSUE TITLE
Missing : documentation about how to test the container locally / on aws

### ISSUE THREAD

**Issue by mcansky** [circleci/image-builder#8]
While the build work it would be good to be able to test run the container locally to verify and test by hand things.

Any examples to run a simple bash console would be appreciated

**Comment by mcansky** [comment]
ping

**Comment by notnoopci** [comment]
@mcansky noted!  Mind if you reach out and we can discuss this and your use-case over email?

**Comment by mcansky** [comment]
@notnoopci I have emailed you, no answer still

**Comment by notnoopci** [comment]
@mcansky I have updated the workflow to be with Docker, and documented testing as well as how to configure CCIE instance to use the custom image: https://github.com/circleci/image-builder-prototype#2-testing-the-container .

**Comment by kimh** [comment]
It seems this issue has been fixed.
