### ISSUE TITLE
PHP 7.0.7 Throws Not Supported Error

### ISSUE THREAD

**Issue by felicianotech** [circleci/image-builder#89]
When building on Trusty w/ PHP 7.0.7, the following error occurs:

> Sorry, we don't support the version of php you specified. Check our list of supported versions and contact us if we should support your version.

PHP 7.0.7 is in the Docker script, via an SSH build I can confirm that the directory and binaries exists in the container, however the builds are failing with the above error message. Building with PHP 7.0.4, the second to newest release we have, seems to work just fine.

Reported on Discuss: https://discuss.circleci.com/t/php-version-not-supported-but-should-be/4866

**Comment by kimh** [comment]
https://github.com/circleci/circle/pull/6635 should fix.
